In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("movie_metadata.csv")
df.head

<bound method NDFrame.head of                  color       director_name  num_critic_for_reviews  duration  \
0                Color       James Cameron                   723.0     178.0
1                Color      Gore Verbinski                   302.0     169.0
2                Color          Sam Mendes                   602.0     148.0
3                Color   Christopher Nolan                   813.0     164.0
4                  NaN         Doug Walker                     NaN       NaN
5                Color      Andrew Stanton                   462.0     132.0
6                Color           Sam Raimi                   392.0     156.0
7                Color        Nathan Greno                   324.0     100.0
8                Color         Joss Whedon                   635.0     141.0
9                Color         David Yates                   375.0     153.0
10               Color         Zack Snyder                   673.0     183.0
11               Color        Bryan Singer                   434.0     169.0
12               Color        Marc Forster                   403.0     106.0
13               Color      Gore Verbinski                   313.0     151.0
14               Color      Gore Verbinski                   450.0     150.0
15               Color         Zack Snyder                   733.0     143.0
16               Color      Andrew Adamson                   258.0     150.0
17               Color         Joss Whedon                   703.0     173.0
18               Color        Rob Marshall                   448.0     136.0
19               Color    Barry Sonnenfeld                   451.0     106.0
20               Color       Peter Jackson                   422.0     164.0
21               Color           Marc Webb                   599.0     153.0
22               Color        Ridley Scott                   343.0     156.0
23               Color       Peter Jackson                   509.0     186.0
24               Color         Chris Weitz                   251.0     113.0
25               Color       Peter Jackson                   446.0     201.0
26               Color       James Cameron                   315.0     194.0
27               Color       Anthony Russo                   516.0     147.0
28               Color          Peter Berg                   377.0     131.0
29               Color     Colin Trevorrow                   644.0     124.0
...                ...                 ...                     ...       ...
5013             Color          Eric Eason                    28.0      79.0
5014             Color            Uwe Boll                    58.0      80.0
5015   Black and White   Richard Linklater                    61.0     100.0
5016             Color     Joseph Mazzella                     NaN      90.0
5017             Color        Travis Legge                     1.0      90.0
5018             Color       Alex Kendrick                     5.0     120.0
5019             Color       Marcus Nispel                    43.0      91.0
5020               NaN     Brandon Landers                     NaN     143.0
5021             Color         Jay Duplass                    51.0      85.0
5022   Black and White          Jim Chuchu                     6.0      60.0
5023             Color          Daryl Wein                    22.0      88.0
5024             Color         Jason Trost                    42.0      78.0
5025             Color         John Waters                    73.0     108.0
5026             Color     Olivier Assayas                    81.0     110.0
5027             Color        Jafar Panahi                    64.0      90.0
5028   Black and White       Ivan Kavanagh                    12.0      83.0
5029             Color    Kiyoshi Kurosawa                    78.0     111.0
5030             Color        Tadeo Garcia                     NaN      84.0
5031             Color  Thomas L. Phillips                    13.0      82.0
5032             Color     Ash Baron-Cohen                    10.0      98.0
5033             Color       Shane Carruth                   143.0      77.0
5034             Color    Neill Dela Llana                    35.0      80.0
5035             Color    Robert Rodriguez                    56.0      81.0
5036             Color     Anthony Vallone                     NaN      84.0
5037             Color        Edward Burns                    14.0      95.0
5038             Color         Scott Smith                     1.0      87.0
5039             Color                 NaN                    43.0      43.0
5040             Color    Benjamin Roberds                    13.0      76.0
5041             Color         Daniel Hsia                    14.0     100.0
5042             Color            Jon Gunn                    43.0      90.0

      director_facebook_likes  actor_3_facebook_likes          actor_2_name  \
0                         0.0                   855.0      Joel David Moore
1                       563.0                  1000.0         Orlando Bloom
2                         0.0                   161.0          Rory Kinnear
3                     22000.0                 23000.0        Christian Bale
4                       131.0                     NaN            Rob Walker
5                       475.0                   530.0       Samantha Morton
6                         0.0                  4000.0          James Franco
7                        15.0                   284.0          Donna Murphy
8                         0.0                 19000.0     Robert Downey Jr.
9                       282.0                 10000.0      Daniel Radcliffe
10                        0.0                  2000.0          Lauren Cohan
11                        0.0                   903.0         Marlon Brando
12                      395.0                   393.0       Mathieu Amalric
13                      563.0                  1000.0         Orlando Bloom
14                      563.0                  1000.0           Ruth Wilson
15                        0.0                   748.0    Christopher Meloni
16                       80.0                   201.0  Pierfrancesco Favino
17                        0.0                 19000.0     Robert Downey Jr.
18                      252.0                  1000.0           Sam Claflin
19                      188.0                   718.0     Michael Stuhlbarg
20                        0.0                   773.0            Adam Brown
21                      464.0                   963.0       Andrew Garfield
22                        0.0                   738.0          William Hurt
23                        0.0                   773.0            Adam Brown
24                      129.0                  1000.0             Eva Green
25                        0.0                    84.0    Thomas Kretschmann
26                        0.0                   794.0          Kate Winslet
27                       94.0                 11000.0    Scarlett Johansson
28                      532.0                   627.0   Alexander Skarsgård
29                      365.0                  1000.0            Judy Greer
...                       ...                     ...                   ...
5013                      3.0                    42.0        Panchito Gómez
5014                    892.0                   492.0    Katharine Isabelle
5015                      0.0                     0.0     Richard Linklater
5016                      0.0                     9.0          Mikaal Bates
5017                    138.0                   138.0         Suzi Lorraine
5018                    589.0                     4.0           Lisa Arnold
5019                    158.0                   265.0       Brittany Curran
5020                      8.0                     8.0       Alana Kaniewski
5021                    157.0                    10.0         Katie Aselton
5022                      0.0                     4.0         Olwenya Maina
5023                     38.0                   211.0         Heather Burns
5024                     91.0                    86.0           Jason Trost
5025                      0.0                   105.0            Mink Stole
5026                    107.0                    45.0        Béatrice Dalle
5027                    397.0                     0.0     Nargess Mamizadeh
5028                     18.0                     0.0         Michael Parle
5029                     62.0                     6.0         Anna Nakagawa
5030                      5.0                    12.0        Michael Cortez
5031                    120.0                    84.0            Joe Coffey
5032                      3.0                   152.0     Stanley B. Herman
5033                    291.0                     8.0        David Sullivan
5034                      0.0                     0.0       Edgar Tancangco
5035                      0.0                     6.0       Peter Marquardt
5036                      2.0                     2.0        John Considine
5037                      0.0                   133.0    Caitlin FitzGerald
5038                      2.0                   318.0         Daphne Zuniga
5039                      NaN                   319.0         Valorie Curry
5040                      0.0                     0.0         Maxwell Moody
5041                      0.0                   489.0         Daniel Henney
5042                     16.0                    16.0      Brian Herzlinger

      actor_1_facebook_likes        gross  \
0                     1000.0  760505847.0
1                    40000.0  309404152.0
2                    11000.0  200074175.0
3                    27000.0  448130642.0
4                      131.0          NaN
5                      640.0   73058679.0
6                    24000.0  336530303.0
7                      799.0  200807262.0
8                    26000.0  458991599.0
9                    25000.0  301956980.0
10                   15000.0  330249062.0
11                   18000.0  200069408.0
12                     451.0  168368427.0
13                   40000.0  423032628.0
14                   40000.0   89289910.0
15                   15000.0  291021565.0
16                   22000.0  141614023.0
17                   26000.0  623279547.0
18                   40000.0  241063875.0
19                   10000.0  179020854.0
20                    5000.0  255108370.0
21                   15000.0  262030663.0
22                     891.0  105219735.0
23                    5000.0  258355354.0
24                   16000.0   70083519.0
25                    6000.0  218051260.0
26                   29000.0  658672302.0
27                   21000.0  407197282.0
28                   14000.0   65173160.0
29                    3000.0  652177271.0
...                      ...          ...
5013                    93.0          NaN
5014                   986.0          NaN
5015                     5.0    1227508.0
5016                   313.0          NaN
5017                   370.0          NaN
5018                    51.0          NaN
5019                   630.0          NaN
5020                   720.0          NaN
5021                   830.0     192467.0
5022                   147.0          NaN
5023                   331.0      76382.0
5024                   407.0          NaN
5025                   462.0     180483.0
5026                   576.0     136007.0
5027                     5.0     673780.0
5028                    10.0          NaN
5029                    89.0      94596.0
5030                    21.0          NaN
5031                   785.0          NaN
5032                   789.0          NaN
5033                   291.0     424760.0
5034                     0.0      70071.0
5035                   121.0    2040920.0
5036                    45.0          NaN
5037                   296.0       4584.0
5038                   637.0          NaN
5039                   841.0          NaN
5040                     0.0          NaN
5041                   946.0      10443.0
5042                    86.0      85222.0

                                                 genres         ...           \
0                       Action|Adventure|Fantasy|Sci-Fi         ...
1                              Action|Adventure|Fantasy         ...
2                             Action|Adventure|Thriller         ...
3                                       Action|Thriller         ...
4                                           Documentary         ...
5                               Action|Adventure|Sci-Fi         ...
6                              Action|Adventure|Romance         ...
7     Adventure|Animation|Comedy|Family|Fantasy|Musi...         ...
8                               Action|Adventure|Sci-Fi         ...
9                      Adventure|Family|Fantasy|Mystery         ...
10                              Action|Adventure|Sci-Fi         ...
11                              Action|Adventure|Sci-Fi         ...
12                                     Action|Adventure         ...
13                             Action|Adventure|Fantasy         ...
14                             Action|Adventure|Western         ...
15                      Action|Adventure|Fantasy|Sci-Fi         ...
16                      Action|Adventure|Family|Fantasy         ...
17                              Action|Adventure|Sci-Fi         ...
18                             Action|Adventure|Fantasy         ...
19        Action|Adventure|Comedy|Family|Fantasy|Sci-Fi         ...
20                                    Adventure|Fantasy         ...
21                             Action|Adventure|Fantasy         ...
22                       Action|Adventure|Drama|History         ...
23                                    Adventure|Fantasy         ...
24                             Adventure|Family|Fantasy         ...
25                       Action|Adventure|Drama|Romance         ...
26                                        Drama|Romance         ...
27                              Action|Adventure|Sci-Fi         ...
28                     Action|Adventure|Sci-Fi|Thriller         ...
29                     Action|Adventure|Sci-Fi|Thriller         ...
...                                                 ...         ...
5013                                       Drama|Family         ...
5014                              Action|Crime|Thriller         ...
5015                                       Comedy|Drama         ...
5016                               Crime|Drama|Thriller         ...
5017                                     Comedy|Romance         ...
5018                                              Drama         ...
5019                            Horror|Mystery|Thriller         ...
5020                              Drama|Horror|Thriller         ...
5021                               Comedy|Drama|Romance         ...
5022                                              Drama         ...
5023                                            Romance         ...
5024                                    Sci-Fi|Thriller         ...
5025                                Comedy|Crime|Horror         ...
5026                                Drama|Music|Romance         ...
5027                                              Drama         ...
5028                                             Horror         ...
5029                      Crime|Horror|Mystery|Thriller         ...
5030                                              Drama         ...
5031                             Comedy|Horror|Thriller         ...
5032                                        Crime|Drama         ...
5033                              Drama|Sci-Fi|Thriller         ...
5034                                           Thriller         ...
5035                Action|Crime|Drama|Romance|Thriller         ...
5036                                        Crime|Drama         ...
5037                                       Comedy|Drama         ...
5038                                       Comedy|Drama         ...
5039                       Crime|Drama|Mystery|Thriller         ...
5040                              Drama|Horror|Thriller         ...
5041                               Comedy|Drama|Romance         ...
5042                                        Documentary         ...

     num_user_for_reviews  language      country  content_rating       budget  \
0                  3054.0   English          USA           PG-13  237000000.0
1                  1238.0   English          USA           PG-13  300000000.0
2                   994.0   English           UK           PG-13  245000000.0
3                  2701.0   English          USA           PG-13  250000000.0
4                     NaN       NaN          NaN             NaN          NaN
5                   738.0   English          USA           PG-13  263700000.0
6                  1902.0   English          USA           PG-13  258000000.0
7                   387.0   English          USA              PG  260000000.0
8                  1117.0   English          USA           PG-13  250000000.0
9                   973.0   English           UK              PG  250000000.0
10                 3018.0   English          USA           PG-13  250000000.0
11                 2367.0   English          USA           PG-13  209000000.0
12                 1243.0   English           UK           PG-13  200000000.0
13                 1832.0   English          USA           PG-13  225000000.0
14                  711.0   English          USA           PG-13  215000000.0
15                 2536.0   English          USA           PG-13  225000000.0
16                  438.0   English          USA              PG  225000000.0
17                 1722.0   English          USA           PG-13  220000000.0
18                  484.0   English          USA           PG-13  250000000.0
19                  341.0   English          USA           PG-13  225000000.0
20                  802.0   English  New Zealand           PG-13  250000000.0
21                 1225.0   English          USA           PG-13  230000000.0
22                  546.0   English          USA           PG-13  200000000.0
23                  951.0   English          USA           PG-13  225000000.0
24                  666.0   English          USA           PG-13  180000000.0
25                 2618.0   English  New Zealand           PG-13  207000000.0
26                 2528.0   English          USA           PG-13  200000000.0
27                 1022.0   English          USA           PG-13  250000000.0
28                  751.0   English          USA           PG-13  209000000.0
29                 1290.0   English          USA           PG-13  150000000.0
...                   ...       ...          ...             ...          ...
5013                 21.0   English          USA             NaN      24000.0
5014                129.0   English       Canada               R          NaN
5015                 80.0   English          USA               R      23000.0
5016                  2.0   English          USA             NaN      25000.0
5017                  3.0   English          USA             NaN      22000.0
5018                 49.0   English          USA             NaN      20000.0
5019                 33.0   English          USA               R          NaN
5020                  8.0   English          USA             NaN      17350.0
5021                 71.0   English          USA               R      15000.0
5022                  1.0   Swahili        Kenya             NaN      15000.0
5023                  8.0   English          USA             NaN      15000.0
5024                 35.0   English          USA         Unrated      20000.0
5025                183.0   English          USA           NC-17      10000.0
5026                 39.0    French       France               R       4500.0

In [5]:
df=df[['num_critic_for_reviews','director_facebook_likes','actor_3_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','imdb_score']]
df.head()

,num_critic_for_reviews,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,imdb_score
0,723.0,0.0,855.0,1000.0,936.0,7.9
1,302.0,563.0,1000.0,40000.0,5000.0,7.1
2,602.0,0.0,161.0,11000.0,393.0,6.8
3,813.0,22000.0,23000.0,27000.0,23000.0,8.5
4,NaN,131.0,NaN,131.0,12.0,7.1

In [6]:
df.isnull().sum()

num_critic_for_reviews      50
director_facebook_likes    104
actor_3_facebook_likes      23
actor_1_facebook_likes       7
actor_2_facebook_likes      13
imdb_score                   0
dtype: int64

In [8]:
for i in df.columns:
    if df[i].isnull().sum()>0:
        df[i]=df[i].fillna(df[i].mean())

In [14]:
from sklearn.neural_network import MLPClassifier
Y=df['imdb_score'].round().values
X=df.drop(['imdb_score'],axis=1).values
classifier=MLPClassifier(hidden_layer_sizes=5,solver='sgd',activation="logistic")

from sklearn.model_selection import KFold
k=KFold(n_splits=10)
for train,test in k.split(X):
    classifier.fit(X[train],Y[train])
    print(classifier.score(X[test],Y[test]))

0.3306930693069307
0.29108910891089107
0.32475247524752476
0.2976190476190476
0.32142857142857145
0.32341269841269843
0.3888888888888889
0.25992063492063494
0.25396825396825395
0.30753968253968256